/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardTenantsIndexRouteImport } from './routes/_dashboard/tenants/index'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/_dashboard/templates/index'
import { Route as DashboardRulesIndexRouteImport } from './routes/_dashboard/rules/index'
import { Route as DashboardPropertiesIndexRouteImport } from './routes/_dashboard/properties/index'
import { Route as DashboardLeadsIndexRouteImport } from './routes/_dashboard/leads/index'
import { Route as DashboardFinanceIndexRouteImport } from './routes/_dashboard/finance/index'
import { Route as DashboardContractsIndexRouteImport } from './routes/_dashboard/contracts/index'
import { Route as DashboardConfigIndexRouteImport } from './routes/_dashboard/config/index'
import { Route as DashboardTenantsNewRouteImport } from './routes/_dashboard/tenants/new'
import { Route as DashboardTenantsTenantIdRouteImport } from './routes/_dashboard/tenants/$tenantId'
import { Route as DashboardPropertiesNewRouteImport } from './routes/_dashboard/properties/new'
import { Route as DashboardPropertiesPropertyIdRouteImport } from './routes/_dashboard/properties/$propertyId'
import { Route as DashboardLeadsLeadIdRouteImport } from './routes/_dashboard/leads/$leadId'
import { Route as DashboardPropertiesPropertyIdEditRouteImport } from './routes/_dashboard/properties/$propertyId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardTenantsIndexRoute = DashboardTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesIndexRoute = DashboardRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesIndexRoute =
  DashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLeadsIndexRoute = DashboardLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsIndexRoute = DashboardContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigIndexRoute = DashboardConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTenantsNewRoute = DashboardTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTenantsTenantIdRoute =
  DashboardTenantsTenantIdRouteImport.update({
    id: '/tenants/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPropertiesNewRoute = DashboardPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesPropertyIdRoute =
  DashboardPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLeadsLeadIdRoute = DashboardLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesPropertyIdEditRoute =
  DashboardPropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardPropertiesPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof DashboardPropertiesNewRoute
  '/tenants/$tenantId': typeof DashboardTenantsTenantIdRoute
  '/tenants/new': typeof DashboardTenantsNewRoute
  '/config/': typeof DashboardConfigIndexRoute
  '/contracts/': typeof DashboardContractsIndexRoute
  '/finance/': typeof DashboardFinanceIndexRoute
  '/leads/': typeof DashboardLeadsIndexRoute
  '/properties/': typeof DashboardPropertiesIndexRoute
  '/rules/': typeof DashboardRulesIndexRoute
  '/templates/': typeof DashboardTemplatesIndexRoute
  '/tenants/': typeof DashboardTenantsIndexRoute
  '/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof DashboardPropertiesNewRoute
  '/tenants/$tenantId': typeof DashboardTenantsTenantIdRoute
  '/tenants/new': typeof DashboardTenantsNewRoute
  '/config': typeof DashboardConfigIndexRoute
  '/contracts': typeof DashboardContractsIndexRoute
  '/finance': typeof DashboardFinanceIndexRoute
  '/leads': typeof DashboardLeadsIndexRoute
  '/properties': typeof DashboardPropertiesIndexRoute
  '/rules': typeof DashboardRulesIndexRoute
  '/templates': typeof DashboardTemplatesIndexRoute
  '/tenants': typeof DashboardTenantsIndexRoute
  '/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/_dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdRouteWithChildren
  '/_dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/_dashboard/tenants/$tenantId': typeof DashboardTenantsTenantIdRoute
  '/_dashboard/tenants/new': typeof DashboardTenantsNewRoute
  '/_dashboard/config/': typeof DashboardConfigIndexRoute
  '/_dashboard/contracts/': typeof DashboardContractsIndexRoute
  '/_dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/_dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/_dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/_dashboard/rules/': typeof DashboardRulesIndexRoute
  '/_dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/_dashboard/tenants/': typeof DashboardTenantsIndexRoute
  '/_dashboard/properties/$propertyId/edit': typeof DashboardPropertiesPropertyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/config/'
    | '/contracts/'
    | '/finance/'
    | '/leads/'
    | '/properties/'
    | '/rules/'
    | '/templates/'
    | '/tenants/'
    | '/properties/$propertyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/config'
    | '/contracts'
    | '/finance'
    | '/leads'
    | '/properties'
    | '/rules'
    | '/templates'
    | '/tenants'
    | '/properties/$propertyId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/'
    | '/_dashboard/leads/$leadId'
    | '/_dashboard/properties/$propertyId'
    | '/_dashboard/properties/new'
    | '/_dashboard/tenants/$tenantId'
    | '/_dashboard/tenants/new'
    | '/_dashboard/config/'
    | '/_dashboard/contracts/'
    | '/_dashboard/finance/'
    | '/_dashboard/leads/'
    | '/_dashboard/properties/'
    | '/_dashboard/rules/'
    | '/_dashboard/templates/'
    | '/_dashboard/tenants/'
    | '/_dashboard/properties/$propertyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/tenants/': {
      id: '/_dashboard/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof DashboardTenantsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/templates/': {
      id: '/_dashboard/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/rules/': {
      id: '/_dashboard/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof DashboardRulesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/': {
      id: '/_dashboard/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof DashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads/': {
      id: '/_dashboard/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof DashboardLeadsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/finance/': {
      id: '/_dashboard/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contracts/': {
      id: '/_dashboard/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof DashboardContractsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/config/': {
      id: '/_dashboard/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof DashboardConfigIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tenants/new': {
      id: '/_dashboard/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof DashboardTenantsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tenants/$tenantId': {
      id: '/_dashboard/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof DashboardTenantsTenantIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/new': {
      id: '/_dashboard/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof DashboardPropertiesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/$propertyId': {
      id: '/_dashboard/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads/$leadId': {
      id: '/_dashboard/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof DashboardLeadsLeadIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/$propertyId/edit': {
      id: '/_dashboard/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdEditRouteImport
      parentRoute: typeof DashboardPropertiesPropertyIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardPropertiesPropertyIdRouteChildren {
  DashboardPropertiesPropertyIdEditRoute: typeof DashboardPropertiesPropertyIdEditRoute
}

const DashboardPropertiesPropertyIdRouteChildren: DashboardPropertiesPropertyIdRouteChildren =
  {
    DashboardPropertiesPropertyIdEditRoute:
      DashboardPropertiesPropertyIdEditRoute,
  }

const DashboardPropertiesPropertyIdRouteWithChildren =
  DashboardPropertiesPropertyIdRoute._addFileChildren(
    DashboardPropertiesPropertyIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLeadsLeadIdRoute: typeof DashboardLeadsLeadIdRoute
  DashboardPropertiesPropertyIdRoute: typeof DashboardPropertiesPropertyIdRouteWithChildren
  DashboardPropertiesNewRoute: typeof DashboardPropertiesNewRoute
  DashboardTenantsTenantIdRoute: typeof DashboardTenantsTenantIdRoute
  DashboardTenantsNewRoute: typeof DashboardTenantsNewRoute
  DashboardConfigIndexRoute: typeof DashboardConfigIndexRoute
  DashboardContractsIndexRoute: typeof DashboardContractsIndexRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
  DashboardLeadsIndexRoute: typeof DashboardLeadsIndexRoute
  DashboardPropertiesIndexRoute: typeof DashboardPropertiesIndexRoute
  DashboardRulesIndexRoute: typeof DashboardRulesIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardTenantsIndexRoute: typeof DashboardTenantsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLeadsLeadIdRoute: DashboardLeadsLeadIdRoute,
  DashboardPropertiesPropertyIdRoute:
    DashboardPropertiesPropertyIdRouteWithChildren,
  DashboardPropertiesNewRoute: DashboardPropertiesNewRoute,
  DashboardTenantsTenantIdRoute: DashboardTenantsTenantIdRoute,
  DashboardTenantsNewRoute: DashboardTenantsNewRoute,
  DashboardConfigIndexRoute: DashboardConfigIndexRoute,
  DashboardContractsIndexRoute: DashboardContractsIndexRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
  DashboardLeadsIndexRoute: DashboardLeadsIndexRoute,
  DashboardPropertiesIndexRoute: DashboardPropertiesIndexRoute,
  DashboardRulesIndexRoute: DashboardRulesIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardTenantsIndexRoute: DashboardTenantsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
