/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardTenantsIndexRouteImport } from './routes/_dashboard/tenants/index'
import { Route as DashboardPropertiesIndexRouteImport } from './routes/_dashboard/properties/index'
import { Route as DashboardLeadsIndexRouteImport } from './routes/_dashboard/leads/index'
import { Route as DashboardPropertiesPropertyIdRouteImport } from './routes/_dashboard/properties/$propertyId'
import { Route as DashboardLeadsLeadIdRouteImport } from './routes/_dashboard/leads/$leadId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardTenantsIndexRoute = DashboardTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesIndexRoute =
  DashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLeadsIndexRoute = DashboardLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesPropertyIdRoute =
  DashboardPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLeadsLeadIdRoute = DashboardLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/properties/$propertyId': typeof DashboardPropertiesPropertyIdRoute
  '/leads/': typeof DashboardLeadsIndexRoute
  '/properties/': typeof DashboardPropertiesIndexRoute
  '/tenants/': typeof DashboardTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/properties/$propertyId': typeof DashboardPropertiesPropertyIdRoute
  '/leads': typeof DashboardLeadsIndexRoute
  '/properties': typeof DashboardPropertiesIndexRoute
  '/tenants': typeof DashboardTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/_dashboard/properties/$propertyId': typeof DashboardPropertiesPropertyIdRoute
  '/_dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/_dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/_dashboard/tenants/': typeof DashboardTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/leads/'
    | '/properties/'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/leads'
    | '/properties'
    | '/tenants'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/'
    | '/_dashboard/leads/$leadId'
    | '/_dashboard/properties/$propertyId'
    | '/_dashboard/leads/'
    | '/_dashboard/properties/'
    | '/_dashboard/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/tenants/': {
      id: '/_dashboard/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof DashboardTenantsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/': {
      id: '/_dashboard/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof DashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads/': {
      id: '/_dashboard/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof DashboardLeadsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/properties/$propertyId': {
      id: '/_dashboard/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof DashboardPropertiesPropertyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads/$leadId': {
      id: '/_dashboard/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof DashboardLeadsLeadIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLeadsLeadIdRoute: typeof DashboardLeadsLeadIdRoute
  DashboardPropertiesPropertyIdRoute: typeof DashboardPropertiesPropertyIdRoute
  DashboardLeadsIndexRoute: typeof DashboardLeadsIndexRoute
  DashboardPropertiesIndexRoute: typeof DashboardPropertiesIndexRoute
  DashboardTenantsIndexRoute: typeof DashboardTenantsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLeadsLeadIdRoute: DashboardLeadsLeadIdRoute,
  DashboardPropertiesPropertyIdRoute: DashboardPropertiesPropertyIdRoute,
  DashboardLeadsIndexRoute: DashboardLeadsIndexRoute,
  DashboardPropertiesIndexRoute: DashboardPropertiesIndexRoute,
  DashboardTenantsIndexRoute: DashboardTenantsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
